In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

In [14]:
component = pd.read_csv('./data/skatingScores/components.csv')
technical = pd.read_csv('./data/skatingScores/technicals.csv').drop(columns = 'Unnamed: 0')
skaters = pd.read_csv('./data/skatingScores/skaters.csv')

In [26]:
technical

,Name,Country,Element,BaseValue,GOETotal,Event,JudgeNationality,IndividualGOE
0,Alysa LIU,USA,3A<<,3.30,-1.65,CRNCUP,J1 ðŸ‡²ðŸ‡½,-5.0
1,Alysa LIU,USA,3Lz,5.90,1.18,CRNCUP,J1 ðŸ‡²ðŸ‡½,1.0
2,Alysa LIU,USA,3Lo,4.90,0.82,CRNCUP,J1 ðŸ‡²ðŸ‡½,1.0
3,Alysa LIU,USA,2A+1Eu+3S,8.10,0.86,CRNCUP,J1 ðŸ‡²ðŸ‡½,2.0
4,Alysa LIU,USA,FCCoSp4,3.50,0.93,CRNCUP,J1 ðŸ‡²ðŸ‡½,2.0
...,...,...,...,...,...,...,...,...
8887,Beres CLEMENTS,CAN,3S,4.73,-2.15,ATMCLA,FIN ðŸ‡«ðŸ‡®,-5
8888,Beres CLEMENTS,CAN,3Lz<,5.19,-2.36,ATMCLA,FIN ðŸ‡«ðŸ‡®,-5
8889,Beres CLEMENTS,CAN,CCoSp3,3.00,0.38,ATMCLA,FIN ðŸ‡«ðŸ‡®,1
8890,Beres CLEMENTS,CAN,StSq23,2.60,-0.07,ATMCLA,FIN ðŸ‡«ðŸ‡®,-1
8891,Beres CLEMENTS,CAN,FCCoSp2,2.50,-0.19,ATMCLA,FIN ðŸ‡«ðŸ‡®,-1

In [30]:
d = technical.groupby(['Event', 'Name'])['BaseValue', 'GOETotal'].sum().reset_index()
technical[(technical['Name'] == 'Yeonjeong PARK') & (technical['Event'] == 'USCLA')].drop_duplicates()


#d[d['Event'] == 'USCLA'].sort_values(by = 'GOETotal', ascending = True)

/Users/winsontruong/anaconda3/envs/iceskating/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.

,Name,Country,Element,BaseValue,GOETotal,Event,JudgeNationality,IndividualGOE
6636,Yeonjeong PARK,KOR,3Lz+3T,10.10,1.77,USCLA,J1 ðŸ‡¨ðŸ‡¦,3
6637,Yeonjeong PARK,KOR,3Lo,4.90,1.63,USCLA,J1 ðŸ‡¨ðŸ‡¦,4
6638,Yeonjeong PARK,KOR,3S,4.30,0.86,USCLA,J1 ðŸ‡¨ðŸ‡¦,2
6639,Yeonjeong PARK,KOR,2A,3.30,0.77,USCLA,J1 ðŸ‡¨ðŸ‡¦,3
6640,Yeonjeong PARK,KOR,CCoSp4,3.50,1.40,USCLA,J1 ðŸ‡¨ðŸ‡¦,4
6641,Yeonjeong PARK,KOR,StSq41,3.90,1.17,USCLA,J1 ðŸ‡¨ðŸ‡¦,3
6642,Yeonjeong PARK,KOR,2A+3T,8.25,1.26,USCLA,J1 ðŸ‡¨ðŸ‡¦,3
6643,Yeonjeong PARK,KOR,3Lz+2T+2Loq,9.79,0.20,USCLA,J1 ðŸ‡¨ðŸ‡¦,1
6644,Yeonjeong PARK,KOR,ChSq12,3.00,1.17,USCLA,J1 ðŸ‡¨ðŸ‡¦,3
6645,Yeonjeong PARK,KOR,3F,5.83,1.59,USCLA,J1 ðŸ‡¨ðŸ‡¦,3
6646,Yeonjeong PARK,KOR,FCSp4,3.20,0.64,USCLA,J1 ðŸ‡¨ðŸ‡¦,2
6647,Yeonjeong PARK,KOR,LSp4,2.70,1.17,USCLA,J1 ðŸ‡¨ðŸ‡¦,5
6648,Yeonjeong PARK,KOR,3Lz+3T,10.10,1.77,USCLA,J2 ðŸ‡¨ðŸ‡¦,3
6649,Yeonjeong PARK,KOR,3Lo,4.90,1.63,USCLA,J2 ðŸ‡¨ðŸ‡¦,4
6650,Yeonjeong PARK,KOR,3S,4.30,0.86,USCLA,J2 ðŸ‡¨ðŸ‡¦,1
6651,Yeonjeong PARK,KOR,2A,3.30,0.77,USCLA,J2 ðŸ‡¨ðŸ‡¦,2
6652,Yeonjeong PARK,KOR,CCoSp4,3.50,1.40,USCLA,J2 ðŸ‡¨ðŸ‡¦,3
6653,Yeonjeong PARK,KOR,StSq41,3.90,1.17,USCLA,J2 ðŸ‡¨ðŸ‡¦,3
6654,Yeonjeong PARK,KOR,2A+3T,8.25,1.26,USCLA,J2 ðŸ‡¨ðŸ‡¦,3
6655,Yeonjeong PARK,KOR,3Lz+2T+2Loq,9.79,0.20,USCLA,J2 ðŸ‡¨ðŸ‡¦,0
6656,Yeonjeong PARK,KOR,ChSq12,3.00,1.17,USCLA,J2 ðŸ‡¨ðŸ‡¦,3
6657,Yeonjeong PARK,KOR,3F,5.83,1.59,USCLA,J2 ðŸ‡¨ðŸ‡¦,3
6658,Yeonjeong PARK,KOR,FCSp4,3.20,0.64,USCLA,J2 ðŸ‡¨ðŸ‡¦,2
6659,Yeonjeong PARK,KOR,LSp4,2.70,1.17,USCLA,J2 ðŸ‡¨ðŸ‡¦,4
6660,Yeonjeong PARK,KOR,3Lz+3T,10.10,1.77,USCLA,J3 ðŸ‡ºðŸ‡¸,4
6661,Yeonjeong PARK,KOR,3Lo,4.90,1.63,USCLA,J3 ðŸ‡ºðŸ‡¸,3
6662,Yeonjeong PARK,KOR,3S,4.30,0.86,USCLA,J3 ðŸ‡ºðŸ‡¸,2
6663,Yeonjeong PARK,KOR,2A,3.30,0.77,USCLA,J3 ðŸ‡ºðŸ‡¸,3
6664,Yeonjeong PARK,KOR,CCoSp4,3.50,1.40,USCLA,J3 ðŸ‡ºðŸ‡¸,4
6665,Yeonjeong PARK,KOR,StSq41,3.90,1.17,USCLA,J3 ðŸ‡ºðŸ‡¸,3
6666,Yeonjeong PARK,KOR,2A+3T,8.25,1.26,USCLA,J3 ðŸ‡ºðŸ‡¸,3
6667,Yeonjeong PARK,KOR,3Lz+2T+2Loq,9.79,0.20,USCLA,J3 ðŸ‡ºðŸ‡¸,1
6668,Yeonjeong PARK,KOR,ChSq12,3.00,1.17,USCLA,J3 ðŸ‡ºðŸ‡¸,2
6669,Yeonjeong PARK,KOR,3F,5.83,1.59,USCLA,J3 ðŸ‡ºðŸ‡¸,3
6670,Yeonjeong PARK,KOR,FCSp4,3.20,0.64,USCLA,J3 ðŸ‡ºðŸ‡¸,3
6671,Yeonjeong PARK,KOR,LSp4,2.70,1.17,USCLA,J3 ðŸ‡ºðŸ‡¸,3
6672,Yeonjeong PARK,KOR,3Lz+3T,10.10,1.77,USCLA,J4 ðŸ‡²ðŸ‡½,3
6673,Yeonjeong PARK,KOR,3Lo,4.90,1.63,USCLA,J4 ðŸ‡²ðŸ‡½,3
6674,Yeonjeong PARK,KOR,3S,4.30,0.86,USCLA,J4 ðŸ‡²ðŸ‡½,2
6675,Yeonjeong PARK,KOR,2A,3.30,0.77,USCLA,J4 ðŸ‡²ðŸ‡½,2
6676,Yeonjeong PARK,KOR,CCoSp4,3.50,1.40,USCLA,J4 ðŸ‡²ðŸ‡½,4
6677,Yeonjeong PARK,KOR,StSq41,3.90,1.17,USCLA,J4 ðŸ‡²ðŸ‡½,4
6678,Yeonjeong PARK,KOR,2A+3T,8.25,1.26,USCLA,J4 ðŸ‡²ðŸ‡½,3
6679,Yeonjeong PARK,KOR,3Lz+2T+2Loq,9.79,0.20,USCLA,J4 ðŸ‡²ðŸ‡½,-1
6680,Yeonjeong PARK,KOR,ChSq12,3.00,1.17,USCLA,J4 ðŸ‡²ðŸ‡½,2
6681,Yeonjeong PARK,KOR,3F,5.83,1.59,USCLA,J4 ðŸ‡²ðŸ‡½,2
6682,Yeonjeong PARK,KOR,FCSp4,3.20,0.64,USCLA,J4 ðŸ‡²ðŸ‡½,2
6683,Yeonjeong PARK,KOR,LSp4,2.70,1.17,USCLA,J4 ðŸ‡²ðŸ‡½,5
6684,Yeonjeong PARK,KOR,3Lz+3T,10.10,1.77,USCLA,J5 ðŸ‡·ðŸ‡º,2
6685,Yeonjeong PARK,KOR,3Lo,4.90,1.63,USCLA,J5 ðŸ‡·ðŸ‡º,2
6686,Yeonjeong PARK,KOR,3S,4.30,0.86,USCLA,J5 ðŸ‡·ðŸ‡º,2
6687,Yeonjeong PARK,KOR,2A,3.30,0.77,USCLA,J5 ðŸ‡·ðŸ‡º,2
6688,Yeonjeong PARK,KOR,CCoSp4,3.50,1.40,USCLA,J5 ðŸ‡·ðŸ‡º,4
6689,Yeonjeong PARK,KOR,StSq41,3.90,1.17,USCLA,J5 ðŸ‡·ðŸ‡º,2
6690,Yeonjeong PARK,KOR,2A+3T,8.25,1.26,USCLA,J5 ðŸ‡·ðŸ‡º,3
6691,Yeonjeong PARK,KOR,3Lz+2T+2Loq,9.79,0.20,USCLA,J5 ðŸ‡·ðŸ‡º,0
6692,Yeonjeong PARK,KOR,ChSq12,3.00,1.17,USCLA,J5 ðŸ‡·ðŸ‡º,2
6693,Yeonjeong PARK,KOR,3F,5.83,1.59,USCLA,J5 ðŸ‡·ðŸ‡º,3
6694,Yeonjeong PARK,KOR,FCSp4,3.20,0.64,USCLA,J5 ðŸ‡·ðŸ‡º,2
6695,Yeonjeong PARK,KOR,LSp4,2.70,1.17,USCLA,J5 ðŸ‡·ðŸ‡º,4

In [21]:
technical['Event'].value_counts()

LOMTRO    4536
CRNCUP    2040
ATMCLA    1176
USCLA     1140
Name: Event, dtype: int64